### ISSUE TITLE
Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by risqaliyevds** [ylacombe/finetune-hf-vits#27]
Traceback (most recent call last):                                                                                                                                                                        
  File "/mnt/sdb/stt/mata/fairseq-mms/finetune-hf-vits/run_vits_finetuning.py", line 1513, in <module>                                                                                                    
    main()                                                                                                                                                                                                
  File "/mnt/sdb/stt/mata/fairseq-mms/finetune-hf-vits/run_vits_finetuning.py", line 1346, in main                                                                                                        
    full_generation = model(**full_generation_sample.to(model.device), speaker_id=speaker_id)                                                                                                             
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl                                                                  
    return self._call_impl(*args, **kwargs)                                                                                                                                                               
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                                                                          
    return forward_call(*args, **kwargs)                                                                                                                                                                  
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward                                                                       
    else self._run_ddp_forward(*inputs, **kwargs)                                                                                                                                                         
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward                                                              
    return self.module(*inputs, **kwargs)  # type: ignore[index]                                                                                                                                          
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl                                                                  
    return self._call_impl(*args, **kwargs)                                                                                                                                                               
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                                                                          
    return forward_call(*args, **kwargs)                                                                                                                                                                  
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/accelerate/utils/operations.py", line 659, in forward                                                                          
    return model_forward(*args, **kwargs)                                                                                                                                                                 
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/accelerate/utils/operations.py", line 647, in __call__                                                                         
    return convert_to_fp32(self.model_forward(*args, **kwargs))                                                                                                                                           
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast                                                                     
    return func(*args, **kwargs)                                                                                                                                                                          
  File "/mnt/sdb/stt/mata/fairseq-mms/finetune-hf-vits/utils/modeling_vits_training.py", line 2151, in forward                                                                                            
    return self._inference_forward(                                                                                                                                                                       
  File "/mnt/sdb/stt/mata/fairseq-mms/finetune-hf-vits/utils/modeling_vits_training.py", line 2000, in _inference_forward                                                                                 
    text_encoder_output = self.text_encoder(                                                                                                                                                              
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl                                                                  
    return self._call_impl(*args, **kwargs)                                                                                                                                                               
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                                                                          
    return forward_call(*args, **kwargs)                                                                                                                                                                  
  File "/mnt/sdb/stt/mata/fairseq-mms/finetune-hf-vits/utils/modeling_vits_training.py", line 1563, in forward                                                                                            
    hidden_states = self.embed_tokens(input_ids) * math.sqrt(self.config.hidden_size)                                                                                                                     
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl                                                                  
    return self._call_impl(*args, **kwargs)                                                                                                                                                               
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/mnt/sdb/stt/mata/fairseq-mms/venvTTS/lib/python3.10/site-packages/torch/nn/functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
VALIDATION - batch 1, process1, waveform torch.Size([8, 108288, 1]), tokens torch.Size([8, 125])

#########

I am getting this error while validation can you check it? I tryed to fine-tune for uzbek (criyllic) language. Here is my dataset 
https://huggingface.co/datasets/mozilla-foundation/common_voice_13_0/viewer/uz

**Comment by risqaliyevds** [comment]
I fond that after processing my audio array comes to array of zeroes it means I am loosing audio. Why it is heppening during processing?

May be that is why I am getting error

**Comment by risqaliyevds** [comment]
I found the reason this error:

Text normalization. If some chars not in tokenizer it will return this error. In validation you hard coded test function that is why for all languages not latin it is returning this error. I somehow fix this but in final still didn't get good result. My trained model returning noisy audio. I is not unlistenable. My dataset was to good.

![image](https://github.com/ylacombe/finetune-hf-vits/assets/115413379/2805b09a-0c99-40dc-ab7c-4b35485b2bd2)

to ->

![image](https://github.com/ylacombe/finetune-hf-vits/assets/115413379/1f770f8d-c903-4ac5-ba46-64599ec86c2f)

**Comment by gpy1234** [comment]
Hi @risqaliyevds I followed your suggestion, but I am still getting the same error.

`RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
`
