### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by vijishmadhavan** [ylacombe/finetune-hf-vits#3]
from transformers import pipeline
import scipy

model_id = "Vijish/vits_mongolian_monospeaker"
synthesiser = pipeline("text-to-speech", model_id) # add device=0 if you want to use a GPU

speech = synthesiser("Монголын бурхан шашинтны төв Гандантэгчэнлин хийдийн Тэргүүн их хамба Д.")

scipy.io.wavfile.write("finetuned_output.wav", rate=speech["sampling_rate"], data=speech["audio"])

Traceback (most recent call last):
  File "D:\finetune-hf-vits\inference.py", line 9, in <module>
    scipy.io.wavfile.write("finetuned_output.wav", rate=speech["sampling_rate"], data=speech["audio"])
  File "D:\finetune-hf-vits\venv\Lib\site-packages\scipy\io\wavfile.py", line 797, in write
    fmt_chunk_data = struct.pack('<HHIIHH', format_tag, channels, fs,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: ushort format requires 0 <= number <= 65535

**Comment by vijishmadhavan** [comment]
Audio Type: <class 'numpy.ndarray'>
Audio Shape: (1, 708608)
Audio Data Type: float32
Sampling Rate: 16000

**Comment by vijishmadhavan** [comment]
I made it work, but get kinda robotic voice, can you help?

**Comment by vijishmadhavan** [comment]
I am getting the same error while trying your model too.
from transformers import pipeline
import scipy

model_id = "ylacombe/mms-spa-finetuned-argentinian-monospeaker"
synthesiser = pipeline("text-to-speech", model_id) # add device=0 if you want to use a GPU

speech = synthesiser("Hola, ¿cómo estás hoy?")

scipy.io.wavfile.write("finetuned_output.wav", rate=speech["sampling_rate"], data=speech["audio"])

**Comment by ylacombe** [comment]
Hey @vijishmadhavan, thanks for opening an issue, I've reproduced your error and fixed it with:
`scipy.io.wavfile.write("finetuned_output.wav", rate=speech["sampling_rate"], data=speech["audio"][0])`

I'll change the README accordingly! thanks for flagging

**Comment by vijishmadhavan** [comment]
**Hey thank you, I trained with 2200 samples for 200 epochs. My results seem to sound wierd. Is this overfitting issue?** 

https://huggingface.co/datasets/Vijish/mozilla_mongolian2
https://huggingface.co/Vijish/mms
https://huggingface.co/Vijish/vits_mongolian_monospeaker

**Comment by vijishmadhavan** [comment]
https://github.com/ylacombe/finetune-hf-vits/assets/53169213/9cb8c2ed-2c13-495f-a88e-62be950d5b81

**Comment by ylacombe** [comment]
Hi @vijishmadhavan, this is a really interesting use-case, thanks for sharing !

A few questions: 
1. Could you send the hyper-parameters that you used?
2. Did you filter your dataset on a single speaker ? You might want to filter your dataset to keep only one speaker. From what I hear, there are a few different speakers in yours. 
3. I don't see the discriminator here: https://huggingface.co/Vijish/mms, did you follow [step 2](https://huggingface.co/Vijish/mms)?


A few recommendations now:
1. You can use wandb to keep track of the log of your experiment -> to better understand where it doesn't learn and to share it here. You have to add [this line](https://github.com/ylacombe/finetune-hf-vits/blob/2809371b04a50cad944efd8031034815b0a271f7/training_config_examples/finetune_mms_kor.json#L5) to your config.
2. Keep in mind that you don't really need 2200 samples but much less.
3. Also keep in mind that the quality of your input dataset will reflect on the generated data
4. If you lower the number of samples (let's say to 200-ish), you can experiment with the hyperparameters. My guess is that you only need to play with the learning rate first. Let me know if that helps

**Comment by vijishmadhavan** [comment]
Hey, Thank you so much, it worked. If the base model did not have emotions in their voice, can finetuning with a nice dataset help with bringing in emotion and sound less robotic.
