### ISSUE TITLE
Who had this error please 

### ISSUE THREAD

**Issue by AdamBenghoula** [ylacombe/finetune-hf-vits#40]
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/home/adem/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/adem/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/adem/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/home/adem/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'run_vits_finetuning.py', './training_config_examples/finetune_mms.json']'

**Comment by benny-png** [comment]
### I get this error too AttributeError: 'NoneType' object has no attribute 'to'

08/03/2024 13:01:14 - INFO - __main__ - ***** Running training *****
08/03/2024 13:01:14 - INFO - __main__ -   Num examples = 125
08/03/2024 13:01:14 - INFO - __main__ -   Num Epochs = 200
08/03/2024 13:01:14 - INFO - __main__ -   Instantaneous batch size per device = 16
08/03/2024 13:01:14 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 16
08/03/2024 13:01:14 - INFO - __main__ -   Gradient Accumulation steps = 1
08/03/2024 13:01:14 - INFO - __main__ -   Total optimization steps = 1600
Steps:   0% 0/1600 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 155, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
TypeError: BatchEncoding.to() got an unexpected keyword argument 'non_blocking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/finetune-hf-vits/run_vits_finetuning.py", line 1494, in <module>
    main()
  File "/content/finetune-hf-vits/run_vits_finetuning.py", line 1090, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 463, in __iter__
    current_batch = send_to_device(current_batch, self.device, non_blocking=self._non_blocking)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 157, in send_to_device
    return tensor.to(device)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 803, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 803, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
AttributeError: 'NoneType' object has no attribute 'to'
wandb: 🚀 View run comic-pine-2 at: https://wandb.ai/mazikuben2-university-of-dar-es-salaam/benn_swahili_vocals/runs/957hc3oy
wandb: ⭐️ View project at: https://wandb.ai/mazikuben2-university-of-dar-es-salaam/benn_swahili_vocals
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240803_130112-957hc3oy/logs
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/finetune-hf-vits/run_vits_finetuning.py', '/content/drive/MyDrive/AUDIO-API/benn_swahili_vocals_config.json']' returned non-zero exit status 1.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Hey you can check [this fix](https://github.com/ylacombe/finetune-hf-vits/issues/22#issuecomment-2027896485) I had the same issue and that fix worked for me @benny-png

**Comment by benny-png** [comment]
@Aml-Hassan-Abd-El-hamid  Live Long mahn 🔥

**Comment by benny-png** [comment]
@AdamBenghoula  might be an issue with your config file...

**Comment by mirodil-ml** [comment]
You get this error when a training data is empty
