### ISSUE TITLE
Unable to run due to 'ValueError: Unable to avoid copy while creating an array as requested.'

### ISSUE THREAD

**Issue by imPdhar** [ylacombe/finetune-hf-vits#44]
I followed this [comment](https://github.com/ylacombe/finetune-hf-vits/issues/22#issuecomment-2027896485) and made changes to the required libraries but in vain. Because all I get is this error (sorry for the verbose logs):

```
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\multiprocess\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\utils\py_utils.py", line 1354, in _write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\arrow_dataset.py", line 3337, in apply_function_on_filtered_inputs
    inputs = format_table(
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\formatting.py", line 629, in format_table
    return formatter(pa_table, query_type=query_type)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\formatting.py", line 396, in __call__
    return self.format_row(pa_table)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\np_formatter.py", line 89, in format_row
    row = self.numpy_arrow_extractor().extract_row(pa_table)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\formatting.py", line 158, in extract_row
    return _unnest(self.extract_batch(pa_table))
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\formatting.py", line 164, in extract_batch
    return {col: self._arrow_array_to_numpy(pa_table[col]) for col in pa_table.column_names}
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\formatting.py", line 164, in <dictcomp>
    return {col: self._arrow_array_to_numpy(pa_table[col]) for col in pa_table.column_names}
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\formatting\formatting.py", line 196, in _arrow_array_to_numpy
    return np.array(array, copy=False)
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Work\MW\STS\TTS\MMS\finetune-hf-vits-main\finetune-hf-vits\run_vits_finetuning.py", line 1494, in <module>
    main()
  File "D:\Work\MW\STS\TTS\MMS\finetune-hf-vits-main\finetune-hf-vits\run_vits_finetuning.py", line 776, in main
    vectorized_datasets = vectorized_datasets.map(
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\dataset_dict.py", line 853, in map
    {
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\dataset_dict.py", line 854, in <dictcomp>
    k: dataset.map(
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\arrow_dataset.py", line 3189, in map
    for rank, done, content in iflatmap_unordered(
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\utils\py_utils.py", line 1394, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\datasets\utils\py_utils.py", line 1394, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\multiprocess\pool.py", line 774, in get
    raise self._value
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
Traceback (most recent call last):
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\accelerate\commands\launch.py", line 994, in launch_command
    simple_launcher(args)
  File "C:\Users\pbapu\anaconda3\envs\fbmms\lib\site-packages\accelerate\commands\launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\pbapu\\anaconda3\\envs\\fbmms\\python.exe', 'run_vits_finetuning.py', 'finetune_mms.json']' returned non-zero exit status 1.
```

If someone can help me with what is wrong with the implementation, that would be great. TIA.

**Comment by imPdhar** [comment]
For reference this is my finetune_mms.json:

```
{
    "project_name": "mms_ara_master_finetuning",
    "push_to_hub": true,
    "hub_model_id": "repo/ara-MMS-UROMAN",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/mms_ara_master_finetuning",

    "dataset_name": "repo/master-mms-ara",
    "audio_column_name": "audio", 
    "text_column_name": "text",
    "train_split_name": "train",
    "eval_split_name": "train",
    "speaker_id_column_name": "speaker_id",
    "override_speaker_embeddings": true,
    "filter_on_speaker_id": 1,

    "full_generation_sample_text": "مرحباً، كيف يمكنني مساعدتك؟",
    
    "max_duration_in_seconds": 20,
    "min_duration_in_seconds": 1.0,
    "max_tokens_length": 500,

    "model_name_or_path": "repo/ara-MMS-UROMAN",


    "preprocessing_num_workers": 1,

    "do_train": true,
    "num_train_epochs": 200,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "per_device_train_batch_size": 2,
    "learning_rate": 2e-5,
    "adam_beta1": 0.8,
    "adam_beta2": 0.99,
    "warmup_ratio": 0.01,
    "group_by_length": false,

    "do_eval": true, 
    "eval_steps": 50,
    "per_device_eval_batch_size": 2,
    "max_eval_samples": 25, 
    "do_step_schedule_per_epoch": true,

    "weight_disc": 3,
    "weight_fmaps": 1,
    "weight_gen": 1,
    "weight_kl": 1.5,
    "weight_duration": 1,
    "weight_mel": 35,

    "fp16": true,
    "seed": 456
}
```

**Comment by imPdhar** [comment]
Doing it on colab seems to solve the problem. Could be a windows problem or shortage of VRAM on my GPU (Mine was a 8GB RTX 4060)
